### ISSUE TITLE
추가할 회원의 이메일이 존재하지 않을때, 발생하는 에러가 앱까지 전달되지 않음

### ISSUE THREAD

**Issue by WraithKim** [plzhelpus/SmartCabinet_CloudFunction#7]
https://github.com/plzhelpus/SmartCabinet_CloudFunction/blob/991ea6633e32bf119e012b02b58a55a8066c66ee/functions/src/index.ts#L143-L148

사용자가 인증 DB에 존재하지 않으면 FirebaseAuthError를 반환하는데 이 예외가 어플리케이션까지 전달되지 않아서. 어플리케이션은 정상적으로 회원이 추가되었다고 판단함.

Firebase에서 출력한 로그
`Unhandled error { Error: There is no user record corresponding to the provided identifier.
    at FirebaseAuthError.Error (native)
    at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:143:16)
    at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:307:15
    at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:712:13
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  errorInfo: 
   { code: 'auth/user-not-found',
     message: 'There is no user record corresponding to the provided identifier.' },
  codePrefix: 'auth' }`

**Comment by WraithKim** [comment]
어플리케이션 코드에서 continueWith 함수에서 호출 결과를 받아와야 에러가 잡힌다는 걸 발견함. => 해결됨
